#from .pergunta1 import df_max_preco
#from .pergunta2 import forca
#from .pergunta3 import defesa
#from .pergunta4 import agilidade
#from .pergunta5 import destreza
#from .pergunta6 import arma
#from .pergunta7 import inicio
#from .pergunta8 import foredef
#from .pergunta9 import precomenor
#from .pergunta10 import comum
